/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Library {
	public static void main(String[] args) {
		someLibraryMethod();
	}
    public static boolean someLibraryMethod() {
    	System.out.println("priya");
    	System.out.println("shukla");
    	System.out.println("Anvesh");
    	System.out.println("Hi");
    	System.out.println("Hi");
    	
    	
        return true;
    }
}
